version: "3"

services:
  postgres:
    restart: always
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5051:80
 
  redis:
    image: redis:5.0.3
    restart: always
    ports:
      - "6379:6379"
      
  initdb:
    build: .
    entrypoint: airflow initdb
    depends_on:
     - postgres

  af_webserver:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    volumes:
      - "./dags:/usr/local/airflow/dags"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    extra_hosts:
      - "hd02:10.10.137.42"
      - "hd03:10.10.137.43"
      - "crawler:10.10.137.10"
      - "db2:10.10.137.31"
      - "crawler_in_db2:10.10.137.31"

  af_flower:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command: flower

  af_scheduler:
    build: .
    restart: always
    depends_on:
      - af_webserver
    volumes:
      - "./dags:/usr/local/airflow/dags"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    command: scheduler
    